// Mapeamento: nomeLogin → nome completo para diplomas
// Chave: exatamente como está em ALUNOS_POR_TURMA (nome do login)
// Valor: nome completo para o diploma

export const NOMES_COMPLETOS = {
  // 8D
  "Alice Tavares":    "Alice da Costa Tavares",
  "Alice Paz":        "Alice Szervinsk Marra Paz",
  "Ana Julia":        "Ana Julia Pires da Costa",
  "Arthur":           "Arthur Souza Linhares",
  "Dandara":          "Dandara Morena Freitas Silva",
  "Francisco":        "Francisco Wallison Carvalho dos Santos",
  "João Pedro":       "João Pedro Candido Martins Nunes",
  "Karolinny":        "Karolinny Brandao Fernandes",
  "Ketelly":          "Ketelly Emanuelly Magalhaes de Souza",
  "Leticia":          "Leticia Amancio Vieira",
  "Lucas Gabriel":    "Lucas Gabriel Sales Marinho",
  "Lucas Matheus":    "Lucas Matheus dos Santos Oliveira",
  "Luis Gabriel":     "Luis Gabriel Alves de Oliveira",
  "Luis Miguel":      "Luis Miguel dos Santos Freitas",
  "Miguel Henrique":  "Miguel Henrique Martins Ferreira",
  "Miguel Nascimento":"Miguel Nascimento de Jesus Pereira",
  "Pedro Riquelme":   "Pedro Riquelme Costa Santos",
  "Thayna":           "Thayna Pereira Araujo",
  "Wanderson":        "Wanderson Bruno da Silva Santos",

  // 8E
  "Caio":             "Caio dos Santos Ferreira",
  "Davi Felipe":      "Davi Felipe Mendes Costa",
  "Davi Henrique":    "Davi Henrique Maciel Araujo",
  "Gabriel":          "Gabriel Louzeiro Martins",
  "Gustavo":          "Gustavo Xavier Alves",
  "Isaque":           "Isaque Soares Gois",
  "Jonathan":         "Jonathan Vitor Almeida Costa",
  "Kauã":             "Kauã Estevan Mendes Rodrigues",
  "Lívia":            "Lívia Eduarda da Silva Freitas",
  "Luiz Felipe":      "Luiz Felipe Virginia Alves",
  "Manuella":         "Manuella Fernandes de Souza Silva",
  "Mateus":           "Mateus Lima Viana",
  "Matheus":          "Matheus de Oliveira Matte",
  "Natanael":         "Natanael Alves Pereira",
  "Natielle":         "Natielle Castelhiano Silva",
  "Nicollas":         "Nicollas Henrique Lima",
  "Paulo":            "Paulo Rocha Lima da Silva",
  "Rafaela":          "Rafaela Sousa Pereira",
  "Rafael":           "Rafael da Silva Macedo",
  "Raissa":           "Raissa Gomes dos Santos",
  "Rebeca":           "Rebeca Ribeiro de Carvalho",
  "Sophie":           "Sophie Nascimento Silva",
  "Talysson":         "Talysson Iago Belarmino Cavalcante",
  "Vicktor":          "Vicktor Gustavo de Jesus Soares",
  "Victor Bernardo":  "Victor Bernardo Sousa Conrado",
  "Victor Manuel":    "Victor Manuel dos Santos Teixeira",
  "William":          "William Borges dos Santos",
  "Yago":             "Yago Henrique Teixeira Brito",
  "João Gabriel":     "João Gabriel Soares da Silva",

  // 8F
  "Anna Beatriz":     "Anna Beatriz Santos de Jesus",
  "Arthur Daniel":    "Arthur Daniel Cristino dos Santos Candido",
  "Arthur Martins":   "Arthur Martins da Silva",
  "Carlos":           "Carlos Francisco Vieira Santanna",
  "Evellyn":          "Evellyn Emmanuelle Graciliano Oliveira",
  "Fábio":            "Fábio Jesus Santos da Silva",
  "Fellype":          "Fellype Ferreira Guedes da Silva",
  "Guilherme":        "Guilherme Silva Velozo da Cruz",
  "Heitor":           "Heitor Emanuel Alves dos Santos",
  "Joao Pedro":       "Joao Pedro Silva dos Santos",
  "Joaquim":          "Joaquim Souza Galiza",
  "Kayla":            "Kayla Sofia Fiel Bispo",
  "Luana":            "Luana Brito Romao",
  "Maria Elisangela": "Maria Elisangela Nascimento dos Santos",
  "Maria Santa":      "Maria Santa Silva Lima",
  "Marlon":           "Marlon Miguel Machado de Carvalho",
  "Mycaela":          "Mycaela Geovana Gomes Melo",
  "Nathalia":         "Nathalia Fernanda Gomes Mendes",
  "Pedro Lucas":      "Pedro Lucas Ramos Silva",
  "Pedro Lukas":      "Pedro Lukas",
  "Renato":           "Renato Renner Junior Silva Soares",
  "Ryan":             "Ryan Lucas Caldeira dos Santos",
  "Sara":             "Sara Lidia da Silva dos Reis",
  "Ycaro":            "Ycaro Júnior Francisca Sobrinho",

  // 8G
  "Ana Gabryella":    "Ana Gabryella Silva de Oliveira",
  "Ana Maria":        "Ana Maria de Souza Alves",
  "Davi Emanoel":     "Davi Emanoel Vieira Veras",
  "Davi Lukas":       "Davi Lukas Alves Ribeiro",
  "Helena":           "Helena Carvalho Gouveia Mendes",
  "Isabela":          "Isabela Souza Franca",
  "Karlos":           "Karlos Andre Alves Mourato",
  "Ketelen":          "Ketelen Cristine Carvalho Costa",
  "Laiza":            "Laiza Fernanda Gonçalves de Sousa",
  "Lorran":           "Lorran Carvalho Sena",
  "Maria Laura":      "Maria Laura de Oliveira Carvalho",
  "Maria Sophia":     "Maria Sophia Oliveira Fontinele",
  "Natalya":          "Natalya Fernandes da Silva Santos",
  "Pablo":            "Pablo Henrique das Chagas Santos",
  "Paulo Henrique":   "Paulo Henrique Gonçalves Castro",
  "Pedro Gabriel":    "Pedro Gabriel de Jesus Abreu Araújo",
  "Pedro Vaz":        "Pedro Henrique Pires de Oliveira Vaz",
  "Pedro Henryque":   "Pedro Henryque Sampaio Fernandes de Sousa",
  "Pietro":           "Pietro Alves Ferreira",
  "Pyetro":           "Pyetro Emanoel Mendes de Souza",
  "Renan":            "Renan Carlos Neves Cavalcante",
  "Sandra":           "Sandra Soares de Almeida",
  "Santiago":         "Santiago Josue Ulacio Pulgar",
  "Thays":            "Thays Oliveira Costa",

  // 8H
  "Anderson":         "Anderson Maranhão Araújo",
  "Bruno":            "Bruno Henrique de Aquino Bastos",
  "Emanuelle":        "Emanuelle Rodrigues de Jesus Pereira",
  "Esllinder":        "Esllinder Esmirna Arvelaez Pineda",
  "Honny":            "Honny Ruth Adrian Hurtado",
  "Laryssa":          "Laryssa Costa dos Reis",
  "Leonardo":         "Leonardo Figueiredo Costa",
  "Levi":             "Levi Dias de Araújo Sousa Santos",
  "Marcus Vinicius":  "Marcus Vinicius de Lima Primo",
  "Maria Fernanda":   "Maria Fernanda Barbosa de Sousa",
  "Matheus Henrique": "Matheus Henrique de Souza Costa",
  "Murillo":          "Murillo Alves da Silva",
  "Nicolas":          "Nicolas Gabriel Mendes dos Santos",
  "Nicolle":          "Nicolle Kristine Lopes Sobrinho",
  "Nicolly":          "Nicolly Moreira dos Santos",
  "Pedro Jorge":      "Pedro Jorge Souza Freitas",
  "Pedro Willian":    "Pedro Willian Hiert da Costa",
  "Rana":             "Rana Melícia Alves Nunes",
  "Riquelme":         "Riquelme Silva Souza",
  "Samuel":           "Samuel de Sousa Cruz",
  "Thayanne":         "Thayanne Victoria Pinto Graca",
  "Victória":         "Victória Sophya Rodrigues dos Santos",
  "Vinícius":         "Vinícius Mendes Ribeiro",
  "Yann":             "Yann Teixeira Lima",
  "Yoxiris":          "Yoxiris Andreina López Barrios",
};

// Nomes que conflitam entre turmas — turma tem prioridade
export const NOMES_POR_TURMA_COMPLETOS = {
  "8E": {
    "Ana Beatriz":    "Ana Beatriz Ferreira Araújo",
    "Arthur":         "Arthur Marques de Sousa",
    "Sofia":          "Sofia Ferreira de Souza",
    "Davi Francisco": "Davi Francisco Carence Almeida",
    "Maria Clara":    "Maria Clara dos Santos Silva",
    "Maria Eduarda":  "Maria Eduarda Rodrigues Schmitt",
    "Yasmin":         "Yasmin Barros Estevao",
  },
  "8F": {
    "Ana Beatriz":    "Ana Beatriz Lima da Silva",
    "Ana Clara":      "Ana Clara de Jesus Lima",
    "Miguel":         "Miguel Alves Ribeiro Neto",
    "Rafael":         "Rafael Sousa de Brito",
    "Sofia":          "Sofia da Silva Oliveira",
    "Victor Conceicao":"Victor Hugo Andrade da Conceicao",
    "Vitor Hugo":     "Vitor Hugo Ferreira Braga de Souza",
    "Wesley":         "Wesley Fernando Sousa Reis",
  },
  "8G": {
    "Ana Clara":      "Ana Clara de Sousa Rosario",
    "Davi Francisco": "Davi Francisco da Silva",
    "Maria Clara":    "Maria Clara Oliveira Gomes",
    "Maria Eduarda":  "Maria Eduarda Vidal Sousa de Jesus",
    "Sophia":         "Sophia Rodrigues do Nascimento",
    "Victor":         "Victor Silva Ribeiro",
  },
  "8H": {
    "Ana Beatriz":    "Ana Beatriz Sampaio Queiroz",
    "Ana Clara":      "Ana Clara Sampaio Queiroz",
    "Ana Gabrieli":   "Ana Gabrieli Nunes Gomes",
    "Sophia":         "Sophia Caroline Oliveira Lima",
    "Victor Hugo":    "Victor Hugo Ribeiro da Silva",
    "Victor Gabriel": "Victor Gabriel dos Santos de Souza",
    "Yasmin":         "Yasmin Eloise Lourenço de Sousa",
  },
};

/**
 * Retorna o nome completo do aluno para uso no diploma.
 * @param {string} turma - ex: "8H"
 * @param {string} nomeLogin - ex: "Murillo"
 * @returns {string} nome completo ou nomeLogin como fallback
 */
export function getNomeCompleto(turma, nomeLogin) {
  const porTurma = NOMES_POR_TURMA_COMPLETOS[turma];
  if (porTurma && porTurma[nomeLogin]) return porTurma[nomeLogin];
  if (NOMES_COMPLETOS[nomeLogin]) return NOMES_COMPLETOS[nomeLogin];
  return nomeLogin;
}
